version: '3'
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server-compose
    ports:
      - "8761:8761"
    networks:
      - survey-network

  config-server:
    image: config-server
    container_name: config-server-compose
    ports:
      - "8088:8088"
    networks:
      - survey-network
    depends_on:
      - eureka-server
    environment:
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"

  load-balancer:
    image: load-balancer-server
    container_name: load-balancer-compose
    ports:
      - "8089:8089"
    networks:
      - survey-network
    depends_on:
      - config-server
    environment:
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  postgres:
    image: postgres:13
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - survey-network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-server
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_COOKIE_SECURE_COOKIE_SAME_SITE: None
      KC_SPI_COOKIE_DEFAULT_COOKIE_SAME_SITE: None
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - survey-network
networks:
  survey-network:
    driver: bridge
