test: hihi
spring:
  application:
    name: SURVEY-SERVICE

  datasource:
    url: jdbc:h2:mem:surveydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082

springdoc:
  api-docs:
    path: SURVEY-SERVICE/swagger-ui/index.html
  swagger-ui:
    path: /swagger-ui.html
