FROM openjdk:17-jdk-alpine
MAINTAINER baeldung.com
COPY target/survey-config-server-0.0.1-SNAPSHOT.jar survey-config-server-0.0.1-SNAPSHOT.jar

EXPOSE 8088
ENTRYPOINT ["java","-jar","survey-config-server-0.0.1-SNAPSHOT.jar"]
