spring:
  cloud:
    config:
      uri: http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/survey-realm
          jwk-set-uri: http://localhost:8080/realms/survey-realm/protocol/openid-connect/certs
