FROM openjdk:17-jdk-alpine
MAINTAINER baeldung.com
COPY target/survery-eureka-server-0.0.1-SNAPSHOT.jar survery-eureka-server-0.0.1-SNAPSHOT.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","survery-eureka-server-0.0.1-SNAPSHOT.jar"]
