eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: GATEWAY-SERVICE
server:
  port: 8089
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE  # lb:// allows load balancing
#          predicates:
#            - Path=/**
#        - id: survey-service
#          uri: lb://SURVEY-SERVICE
#          predicates:
#            - Path=/surveys/**
