server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YGWoah/survey-project.git
          default-label: main  # or 'main' depending on your GitHub default branch
          username: YGWoah
          password: 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
#          search-paths: /path/to/config-folder