server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: /home/yg-woah/DevFolders/survey-config-repo
          default-label: master  # or 'master' depending on your GitHub default branch
#          search-paths: /*